create table html_features
(
    id                                   bigint                   primary key,
    visit_id                             varchar(26)              not null,
    crawl_timestamp                      timestamp with time zone not null,
    domain_name                          varchar(128)             not null,
    nb_imgs                              integer,
    nb_links_int                         integer,
    nb_links_ext                         integer,
    nb_links_tel                         integer,
    nb_links_email                       integer,
    nb_input_txt                         integer,
    nb_button                            integer,
    nb_meta_desc                         integer,
    nb_meta_keyw                         integer,
    nb_numerical_strings                 integer,
    nb_tags                              integer,
    nb_words                             integer,
    title                                varchar(2000),
    htmlstruct                           varchar(2000),
    body_text                            text,
    meta_text                            text,
    url                                  varchar(255),
    body_text_truncated                  boolean,
    meta_text_truncated                  boolean,
    title_truncated                      boolean,
    nb_letters                           integer,
    nb_distinct_hosts_in_urls            integer,
    external_hosts                       jsonb,
    nb_facebook_deep_links               integer,
    nb_facebook_shallow_links            integer,
    nb_linkedin_deep_links               integer,
    nb_linkedin_shallow_links            integer,
    nb_twitter_deep_links                integer,
    nb_twitter_shallow_links             integer,
    nb_currency_names                    integer,
    nb_distinct_currencies               integer,
    distance_title_final_dn              integer,
    longest_subsequence_title_final_dn   integer,
    facebook_links                       varchar[],
    twitter_links                        varchar[],
    linkedin_links                       varchar[],
    youtube_links                        varchar[],
    vimeo_links                          varchar[],
    nb_youtube_deep_links                integer,
    nb_youtube_shallow_links             integer,
    nb_vimeo_deep_links                  integer,
    nb_vimeo_shallow_links               integer,
    body_text_language                   varchar(128),
    body_text_language_2                 varchar(128),
    fraction_words_title_initial_dn      double precision,
    fraction_words_title_final_dn        double precision,
    nb_distinct_words_in_title           integer,
    distance_title_initial_dn            integer,
    longest_subsequence_title_initial_dn integer,
)


--     proba_low_content                    double precision,
--     is_low_content                       boolean,
--     proba_fake_shop                      double precision,
--     is_fake_shop                         boolean
--
-- constraint html_visit_url_uq
--         unique (visit_id, url)


