# Default values for muppets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dnsbelgium/mercator/muppets
  pullPolicy: IfNotPresent
  tag: k8s

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ""
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"

podSecurityContext:
  runAsUser: 65534
  fsGroup: 65534
  supplementalGroups:
    - 65534

securityContext:
  runAsUser: 65534
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - SYS_ADMIN
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 500m
    memory: 1024M
  limits:
    cpu: 500m
    memory: 1024M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

s3_bucket:
sqs_input_queue:
sqs_output_queue:
limits:
  # Max length in bytes.
  # TODO: split for html and image?
  max_content_length: 10485760
  # When to try taking a webp instead of a png
  # 3 mebibyte
  png_threshold: 3145728
  # Percentage of total request that produced an error before unhealthy
  failure_threshold: 0.05

extraEnv: {}

global:
  # environment to deploy to, can be "local" or "aws"
  environment: "local"
  region: "eu-west-1"
  vpc:
    endpoint_cidr:
      - "127.0.0.1/32"

updateStrategy: Recreate

networkPolicy:
  enabled: true
  ingress:
    from:
      - namespaceSelector:
          matchLabels:
            namespace: monitoring
        podSelector:
          matchLabels:
            app: prometheus

podMonitor:
  enabled: false
  port: http
  scheme: http
  insecureSkipVerify: true
  interval: 15s
  ## [Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheus-operator-1)
  ## [Kube Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#exporters)
  # serviceMonitor.selector -- Default to kube-prometheus install (CoreOS recommended), but should be set according to Prometheus install.
  selector:
    release: kube-prometheus-stack
  path: /actuator/prometheus
  annotations: {}
  metricRelabelings: {}

prometheusRule:
  enabled: false
  failure_rate: 0.01
  period: 5m
