# Default values for feature-extraction.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "dnsbelgium/mercator/ssl-crawler"
  pullPolicy: IfNotPresent
  tag: k8s

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ""
  name: ""

podAnnotations:
  prometheus.io/scrape_https: "true"
  prometheus.io/port: "8443"
  prometheus.io/path: "/"
  prometheus.io/scheme: "https"
#  fluentbit.io/parser: log4j-jsonevent-layout

podSecurityContext:
  runAsUser: 10000
  fsGroup: 10000
  supplementalGroups:
    - 10000

securityContext:
  runAsUser: 10000
  readOnlyRootFilesystem: true
  privileged: false
  runAsNonRoot: true
  capabilities:
    drop:
      - all

resources:
  requests:
    cpu: 500m
    memory: 600M
  limits:
    cpu: 500m
    memory: 750M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

queue_in:
queue_ack:
database:
  name: "postgres"
  host: "localhost"
  username: "postgres"
  password: "password"
  schema: "ssl_crawler"

global:
  # environment to deploy to, can be "local" or "aws"
  environment: "local"
  region: "eu-west-1"
  vpc:
    db_cidr:
      - "127.0.0.1/32"
    endpoint_cidr:
      - "127.0.0.1/32"

updateStrategy: Recreate
