apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feature-extraction.fullname" . }}
  labels:
  {{- include "feature-extraction.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_CONTENT_PASSWORD: "{{ .Values.database.password }}"
