repos:
- repo: https://github.com/gherynos/pre-commit-java
  rev: v0.6.9
  hooks:
    #- id: pmd
    #  exclude: /test/
    - id: cpd
      exclude: /test/
    #- id: checkstyle
    #  exclude: /test/
- repo: https://github.com/ejba/pre-commit-maven
  rev: v0.3.4
  hooks:
  -   id: maven
      args: ['verify -Dsnyk.skip']
  #-   id: maven-spotless-apply