services:

  mercator:
    image: dnsbelgium/mercator:latest
    volumes:
      - mercator_data:/root/mercator
    ports:
      - '8082:8082'
    environment:
      SMTP_ENABLED: false
      VAT_CRAWLER_MAX_VISITS_PER_DOMAIN: 2
    healthcheck:
      test: "rm -f health && wget -q localhost:8082/actuator/health && grep UP health > /dev/null"
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 3s

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_started
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana-admin-username
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana-admin-password
    secrets:
      - grafana-admin-username
      - grafana-admin-password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # To debug connection to AWS locally. Doesn't need to be deployed for normal development/running
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DEFAULT_BUCKETS: mercator
    deploy:
      replicas: 0

volumes:
  grafana-storage:
  prom_data:
  mercator_data:
secrets:
  # define with:
  # ```
  # echo "yourusername" | docker secret create grafana-admin-username -
  # ```
  grafana-admin-username:
    external: true
  # define with:
  # ```
  # echo "yourpassword" | docker secret create grafana-admin-username -
  # ```
  grafana-admin-password:
    external: true
