{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mercator-ui.fullname" . }}
  labels:
  {{- include "mercator-ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mercator-ui.selectorLabels" . | nindent 6 }}
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    - from:
        {{- with .from }}{{- . | toYaml | nindent 8 }}{{- else }} []{{- end }}
      ports:
        - protocol: "TCP"
          port: 8080
    {{- end }}
  egress: []
  policyTypes:
    - Ingress
    - Egress
{{- end }}