apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mercator-api.fullname" . }}
  labels:
  {{- include "mercator-api.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_DISPATCHER_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_CONTENT_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_DNS_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_SMTP_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_FEATURE_EXTRACTION_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_VAT_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATASOURCE_TLS_PASSWORD: "{{ .Values.database.password }}"
