{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mercator-api.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  annotations:
{{ toYaml .Values.serviceMonitor.annotations | indent 4 }}
  labels:
    {{- include "mercator-api.labels" . | nindent 4 }}
  {{- range $key, $value := .Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    matchLabels:
{{ include "mercator-api.selectorLabels" . | indent 6 }}
  endpoints:
  - port: http
    scheme: https
    tls_config:
      insecureSkipVerify: true
    interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.path }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 6) . }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
{{ end }}