with typed as (
    select *
    from read_json(coalesce(getvariable('jsonLocation'), '~/mercator/json/web/*.json'),
                   columns={
                       visit_id: 'VARCHAR',
                       domain_name: 'VARCHAR',
                       matching_url: 'VARCHAR',
                       crawl_started: 'TIMESTAMP',
                       crawl_finished: 'TIMESTAMP',
                       vat_values: 'VARCHAR[]',
                       visited_urls: 'VARCHAR[]',
                       page_visits: 'STRUCT(
                                    crawl_started TIMESTAMP,
                                    crawl_finished TIMESTAMP,
                                    status_code INTEGER,
                                    url VARCHAR,
                                    final_url VARCHAR,
                                    link_text VARCHAR,
                                    path VARCHAR,
                                    response_body VARCHAR,
                                    headers MAP(VARCHAR, VARCHAR[]),
                                    content_length INTEGER,
                                    vat_values VARCHAR[]
                                )[]',
                       html_features: 'STRUCT(
                                       url VARCHAR,
                                       nb_imgs INTEGER,
                                       nb_links_int INTEGER,
                                       nb_links_ext INTEGER,
                                       nb_links_tel INTEGER,
                                       nb_links_email INTEGER,
                                       nb_input_txt INTEGER,
                                       nb_button INTEGER,
                                       nb_meta_desc INTEGER,
                                       nb_meta_keyw INTEGER,
                                       nb_numerical_strings INTEGER,
                                       nb_tags INTEGER,
                                       nb_words INTEGER,
                                       nb_letters INTEGER,
                                       html_length INTEGER,
                                       nb_facebook_shallow_links INTEGER,
                                       nb_facebook_deep_links INTEGER,
                                       nb_linkedin_deep_links INTEGER,
                                       nb_linkedin_shallow_links INTEGER,
                                       nb_twitter_deep_links INTEGER,
                                       nb_twitter_shallow_links INTEGER,
                                       nb_youtube_deep_links INTEGER,
                                       nb_youtube_shallow_links INTEGER,
                                       nb_vimeo_deep_links INTEGER,
                                       nb_vimeo_shallow_links INTEGER,
                                       nb_currency_names INTEGER,
                                       nb_distinct_currencies INTEGER,
                                       distance_title_final_dn INTEGER,
                                       distance_title_initial_dn INTEGER,
                                       longest_subsequence_title_final_dn INTEGER,
                                       longest_subsequence_title_initial_dn INTEGER,
                                       fraction_words_title_final_dn DOUBLE,
                                       fraction_words_title_initial_dn DOUBLE,
                                       nb_distinct_words_in_title INTEGER,
                                       body_text_language VARCHAR,
                                       body_text_language_2 VARCHAR,
                                       nb_distinct_hosts_in_urls INTEGER,
                                       external_hosts VARCHAR [],
                                       facebook_links VARCHAR [],
                                       twitter_links VARCHAR [],
                                       linkedin_links VARCHAR [],
                                       youtube_links VARCHAR [],
                                       vimeo_links VARCHAR [],
                                       title VARCHAR,
                                       htmlstruct VARCHAR,
                                       body_text VARCHAR,
                                       meta_text VARCHAR,
                                       body_text_truncated BOOLEAN,
                                       meta_text_truncated BOOLEAN,
                                       title_truncated BOOLEAN
                                     )[]',
                       detected_technologies: 'VARCHAR []'})
),
added_year_month as (
    select *, year(crawl_started) as year, month(crawl_started) as month
    from typed
)