apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "muppets.fullname" . }}
  labels:
  {{- include "muppets.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "muppets.selectorLabels" . | nindent 6 }}
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    - from:
        {{- with .from }}{{- . | toYaml | nindent 8 }}{{- else }} []{{- end }}
      ports:
        - protocol: "TCP"
          port: 8080
    {{- end }}
  egress:
    # vpc endpoints
    - ports:
        - port: 443
      to:
        {{- range .Values.global.vpc.endpoint_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
    # website crawling http
    - ports:
        - port: 80
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
    # website crawling https
    - ports:
        - port: 443
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
  policyTypes:
    - Ingress
    - Egress
