apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dispatcher.fullname" . }}
  labels:
  {{- include "dispatcher.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
