apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssl-crawler.fullname" . }}
  labels:
    {{- include "ssl-crawler.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
    {{- include "ssl-crawler.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "ssl-crawler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssl-crawler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: http*/}}
{{/*              scheme: HTTPS*/}}
{{/*            periodSeconds: 10*/}}
{{/*            failureThreshold: 5*/}}
{{/*            timeoutSeconds: 10*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "ssl-crawler.fullname" . }}
            {{ if eq .Values.global.environment "local" }}
            - configMapRef:
                name: "{{ include "ssl-crawler.fullname" . }}-local"
            {{ else }}
            - configMapRef:
                name: "{{ include "ssl-crawler.fullname" . }}-aws"
            {{ end }}
            {{ if eq .Values.global.environment "aws" }}
            - secretRef:
                name: "{{ include "ssl-crawler.fullname" . }}"
            {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
