apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssl-crawler.fullname" . }}
  labels:
  {{- include "ssl-crawler.labels" . | nindent 4 }}
stringData:
  SSL_CRAWLER_DB_PASSWORD: "{{ .Values.database.password }}"
