# Default values for ground-truth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dnsbelgium/mercator/ground-truth
  pullPolicy: IfNotPresent
  tag: k8s

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ""
  name: ""

podSecurityContext:
  runAsUser: 10000
  fsGroup: 10000
  supplementalGroups:
    - 10000

securityContext:
  runAsUser: 10000
  readOnlyRootFilesystem: true
  privileged: false
  runAsNonRoot: true
  capabilities:
    drop:
      - all

resources:
  requests:
    cpu: 100m
    memory: 600M
  limits:
    cpu: 500m
    memory: 600M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# environment to deploy to, can be "local" or "aws"
environment: "local"
region: "eu-west-1"
database:
  url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=ground_truth"
  schema: "ground_truth"
  username: "postgres"
  password: "password"

global:
  vpc:
    db_cidr:
      - "127.0.0.1/32"
    endpoint_cidr:
      - "127.0.0.1/32"

updateStrategy: Recreate
