apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ground-truth.fullname" . }}
  labels:
  {{- include "ground-truth.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ground-truth.selectorLabels" . | nindent 6 }}
  egress:
    # vpc endpoints
    - ports:
        - port: 443
      to:
        {{- range .Values.global.vpc.endpoint_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
    # database
    - ports:
        - port: 5432
      to:
        {{- range .Values.global.vpc.db_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
  policyTypes:
    - Egress
