apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ground-truth.fullname" . }}
  labels:
  {{- include "ground-truth.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
