apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dns-crawler.fullname" . }}
  labels:
  {{- include "dns-crawler.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
  GEO_IP_MAXMIND_LICENSE_KEY: "{{ .Values.geoip.key }}"
