# Default values for localstack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localstack/localstack
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 10000
  fsGroup: 10000
  supplementalGroups:
    - 10000

securityContext:
  runAsUser: 10000
  readOnlyRootFilesystem: true
  privileged: false
  runAsNonRoot: true
  capabilities:
    drop:
      - all

service:
  type: NodePort
  ports:
  - name: "edge"
    port: 4566
    targetPort: 4566
  - name: "http"
    port: 8080
    targetPort: 8080

resources:
  requests:
    cpu: 1000m
    memory: 128MiB
  limits:
    cpu: 1
    memory: 512MiB


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

project_dir: ''
