apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tls-crawler.fullname" . }}
  labels:
    {{- include "tls-crawler.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
    {{- include "tls-crawler.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "tls-crawler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tls-crawler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTPS
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "tls-crawler.fullname" . }}
            {{ if eq .Values.global.environment "local" }}
            - configMapRef:
                name: "{{ include "tls-crawler.fullname" . }}-local"
            {{ else }}
            - configMapRef:
                name: "{{ include "tls-crawler.fullname" . }}-aws"
            {{ end }}
            - secretRef:
                name: "{{ include "tls-crawler.fullname" . }}"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 450M
      dnsConfig:
        options:
          - name: ndots
            value: "1"