apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tls-crawler.fullname" . }}
  labels:
  {{- include "tls-crawler.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tls-crawler.selectorLabels" . | nindent 6 }}
  ingress:
    # Prometheus
    - ports:
        - port: 8443
      from:
        - namespaceSelector:
            matchLabels:
              namespace: monitoring
        - podSelector:
            matchLabels:
              app: prometheus
  egress:
    # vpc endpoints
    - ports:
        - port: 443
      to:
        {{- range .Values.global.vpc.endpoint_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
    # database
    - ports:
        - port: 5432
      to:
        {{- range .Values.global.vpc.db_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
    # TLS crawling
    - ports:
        - port: 80
        - port: 443
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
  policyTypes:
    - Ingress
    - Egress
