{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "tls-crawler.fullname" . }}
  labels:
    {{- include "tls-crawler.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  groups:
    - name: {{ include "tls-crawler.fullname" . }}
      rules:
        - alert: MercatorTLSCrawlerMaxFailuresExceeded
          expr: sum by(namespace)(increase(tls_crawler_visits_failed_total{namespace='{{ .Release.Namespace }}'}[{{ .Values.prometheusRule.period }}])) > {{ .Values.prometheusRule.max_failures}}
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "{{ .Chart.Name }} has failed too often"
            description: "{{ .Chart.Name }} has failed {{ "{{" }} $value {{ "}}" }} times in the last {{ .Values.prometheusRule.period }} in namespace {{ .Release.Namespace }} (max: {{ .Values.prometheusRule.max_failures}} )."
{{- end }}
