{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "tls-crawler.fullname" . }}
  labels:
    {{- include "tls-crawler.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  groups:
    - name: {{ include "tls-crawler.fullname" . }}
      rules:
        - alert: FailureRateError
          expr: sum by(kubernetes_namespace)(increase(tls_crawler_visits_failed_total{kubernetes_namespace='{{ .Release.Namespace }}'}[{{ .Values.prometheus.period }}])) / sum by(kubernetes_namespace)(increase(tls_crawler_visits_completed_total{kubernetes_namespace='{{ .Release.Namespace }}'}[{{ .Values.prometheus.period }}])) < {{ .Values.prometheus.failure_rate}}
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Crawler failure rate too high (namespace {{ .Release.Namespace }})"
            description: "Crawler failure rate in namespace {{ .Release.Namespace }}) is {{ "{{" }} $value {{ "}}" }} in the last {{ .Values.prometheus.period }}, which is higher than 1%."
{{- end }}
