apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tls-crawler.fullname" . }}
  labels:
  {{- include "tls-crawler.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
