{
 "title": "Mercator",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_gc_overhead,instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate interval", "query": "1s,5s,10s,20s,30s,60s,120s" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Threads active per module",
   "type": "timeseries",
   "description": "Shows how many threads are busy in one of these parts of the code.",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "threads_tls{instance=\"$instance\"}",
     "legendFormat": "TLS"
    },
    {
     "expr": "threads_smtp{instance=\"$instance\"}",
     "legendFormat": "SMTP"
    },
    {
     "expr": "threads_save{instance=\"$instance\"}",
     "legendFormat": "Save"
    },
    {
     "expr": "threads_post_save{instance=\"$instance\"}",
     "legendFormat": "Post_Save"
    },
    {
     "expr": "threads_dns{instance=\"$instance\"}",
     "legendFormat": "DNS"
    },
    {
     "expr": "threads_web{instance=\"$instance\"}",
     "legendFormat": "WEB"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Daemon threads"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "Live threads"
    },
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_started_threads_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TLS crawl rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(tls_crawler_visits_completed_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Crawls/sec"
    }
   ]
  },
  {
   "title": "TLS cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(tls_crawler_scanresult_cache_misses_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Cache misses/sec"
    },
    {
     "expr": "rate(tls_crawler_scanresult_cache_hits_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Cache hits/sec"
    }
   ]
  },
  {
   "title": "TLS cache size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tls_crawler_scanresult_cache_size{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WEB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Names/sec",
   "type": "timeseries",
   "description": "Web crawls per second\n(one crawl = multiple page fetches)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(web_crawls_done_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Crawls/sec"
    }
   ]
  },
  {
   "title": "Total pages fetched",
   "type": "stat",
   "description": "Total number of pages fetched so far.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vat_crawler_pages_fetched_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages failed",
   "type": "stat",
   "description": "Total number of pages that could not be fetched for some reason.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vat_crawler_pages_failed_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(vat_crawler_pages_fetched_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "fetched/sec"
    }
   ]
  },
  {
   "title": "Failed page fetches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(vat_crawler_pages_failed_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Failed pages/sec"
    }
   ]
  },
  {
   "title": "Fetch duration",
   "type": "timeseries",
   "description": "Avg time to fetch a web page",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vat_crawler_page_body_fetched_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(vat_crawler_page_body_fetched_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Avg duration page fetch"
    }
   ]
  },
  {
   "title": "Web cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(vat_crawler_okhttp_cache_hit_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Hit count"
    },
    {
     "expr": "rate(vat_crawler_okhttp_cache_network_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Miss count"
    }
   ]
  },
  {
   "title": "Web Cache size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vat_crawler_okhttp_cache_size_bytes",
     "legendFormat": "Cache size"
    }
   ]
  },
  { "title": "SMTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Names/sec",
   "type": "timeseries",
   "description": "Number of domain names visited by SMTP crawler per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(smtp_analyzer_domains_done_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Visits/sec"
    }
   ]
  },
  {
   "title": "SMTP crawls ongoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "smtp_crawls_ongoing{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP's/sec",
   "type": "timeseries",
   "description": "Number of IP's visited per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(smtp_crawl_ip_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "IP's visited"
    }
   ]
  },
  {
   "title": "SMTP crawls done",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smtp_analyzer_domains_done_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMTP cache size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smtp_analyzer_cache_size{instance=\"$instance\"}",
     "legendFormat": "SMTP cache size"
    }
   ]
  },
  {
   "title": "SMTP visit duration ",
   "type": "timeseries",
   "description": "Avg time needed to visit one domain name",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(smtp_crawl_ip_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(smtp_crawl_ip_seconds_count[$rate_interval])",
     "legendFormat": "Duration per IP"
    }
   ]
  }
 ]
}