{
 "title": "Monocator v2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_gc_overhead,instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate interval", "query": "1s,5s,10s,20s,30s,60s,120s" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Shows how many threads are busy in one of these parts of the code.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "threads_tls{instance=\"$instance\"}",
     "legendFormat": "TLS"
    },
    {
     "expr": "threads_smtp{instance=\"$instance\"}",
     "legendFormat": "SMTP"
    },
    {
     "expr": "threads_save{instance=\"$instance\"}",
     "legendFormat": "Save"
    },
    {
     "expr": "threads_post_save{instance=\"$instance\"}",
     "legendFormat": "Post_Save"
    },
    {
     "expr": "threads_dns{instance=\"$instance\"}",
     "legendFormat": "DNS"
    },
    {
     "expr": "threads_web{instance=\"$instance\"}",
     "legendFormat": "WEB"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_started_threads_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy threads excluding SMTP",
   "type": "timeseries",
   "description": "Shows how many threads are busy in one of these parts of the code.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "threads_tls{instance=\"$instance\"}",
     "legendFormat": "TLS"
    },
    {
     "expr": "threads_save{instance=\"$instance\"}",
     "legendFormat": "Save"
    },
    {
     "expr": "threads_post_save{instance=\"$instance\"}",
     "legendFormat": "Post_Save"
    },
    {
     "expr": "threads_dns{instance=\"$instance\"}",
     "legendFormat": "DNS"
    },
    {
     "expr": "threads_web{instance=\"$instance\"}",
     "legendFormat": "WEB"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 14, "y": 11 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Daemon threads"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "Live threads"
    },
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Save rate",
   "type": "timeseries",
   "description": "Number of saves per second.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(repository_save_dns_crawlresult_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Save DNS/sec"
    },
    {
     "expr": "rate(repository_save_html_features_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Save Features/sec"
    }
   ]
  },
  {
   "title": "Saves successful",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "save_visitResult_seconds_count{exception=\"none\", instance=\"$instance\"}",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Save latency",
   "type": "timeseries",
   "description": "Time it takes to save entries in teh database",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(repository_save_dns_crawlresult_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(repository_save_dns_crawlresult_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Save DNS"
    },
    {
     "expr": "rate(repository_save_html_features_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(repository_save_html_features_seconds_count[$rate_interval])",
     "legendFormat": "Save Features"
    }
   ]
  },
  {
   "title": "Saves failed",
   "type": "stat",
   "description": "Saves that generated an exception",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(save_visitResult_seconds_count{exception!=\"none\"})OR on() vector(0)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Save latency",
   "type": "timeseries",
   "description": "Time it takes to save entries in teh database",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(repository_insert_dns_request_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(repository_insert_dns_request_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "dns_request"
    },
    {
     "expr": "rate(repository_insert_dns_response_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_insert_dns_response_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "dns_response"
    },
    {
     "expr": "rate(repository_insert_tls_certificate_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_insert_tls_certificate_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "tls_certificate"
    },
    {
     "expr": "rate(repository_insert_tls_full_scan_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_insert_tls_full_scan_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "tls_full_scan"
    },
    {
     "expr": "rate(repository_insert_tls_crawl_result_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_insert_tls_crawl_result_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "tls_crawl_result"
    },
    {
     "expr": "rate(repository_insert_web_visit_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_insert_web_visit_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "web_visit"
    },
    {
     "expr": "rate(repository_insert_web_page_visit_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_insert_web_page_visit_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "web_page_visit"
    },
    {
     "expr": "rate(repository_save_html_features_seconds_sum{instance=\"$instance\"}[$rate_interval])/rate(repository_save_html_features_seconds_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "html_features"
    }
   ]
  },
  {
   "title": "Duration saving VisitResult",
   "type": "timeseries",
   "description": "The average time it takes to save a VisitResult.\nThis consists of several inserts (for all modules).\nIt only includes the successful saves.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(save_visitResult_seconds_sum{exception=\"none\", instance=\"$instance\"}[$rate_interval]) / rate(save_visitResult_seconds_count[$rate_interval])",
     "legendFormat": "Avg duration successful saves"
    }
   ]
  },
  { "title": "TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "TLS crawl rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(tls_crawler_visits_completed_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Crawls/sec"
    }
   ]
  },
  {
   "title": "TLS cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(tls_crawler_scanresult_cache_misses_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Cache misses/sec"
    },
    {
     "expr": "rate(tls_crawler_scanresult_cache_hits_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Cache hits/sec"
    }
   ]
  },
  {
   "title": "TLS cache size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tls_crawler_scanresult_cache_size{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WEB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Names/sec",
   "type": "timeseries",
   "description": "Web crawls per second\n(one crawl = multiple page fetches)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(web_crawls_done_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Crawls/sec"
    }
   ]
  },
  {
   "title": "Total pages fetched",
   "type": "stat",
   "description": "Total number of pages fetched so far.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vat_crawler_pages_fetched_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages failed",
   "type": "stat",
   "description": "Total number of pages that could not be fetched for some reason.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vat_crawler_pages_failed_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "rate(vat_crawler_pages_fetched_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "fetched/sec"
    }
   ]
  },
  {
   "title": "Failed page fetches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "rate(vat_crawler_pages_failed_total{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Failed pages/sec"
    }
   ]
  },
  {
   "title": "Fetch duration",
   "type": "timeseries",
   "description": "Avg time to fetch a web page",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vat_crawler_page_body_fetched_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(vat_crawler_page_body_fetched_seconds_count[$rate_interval])",
     "legendFormat": "Avg duration page fetch"
    }
   ]
  },
  {
   "title": "Web cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "rate(vat_crawler_okhttp_cache_hit_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Hit count"
    },
    {
     "expr": "rate(vat_crawler_okhttp_cache_network_count{instance=\"$instance\"}[$rate_interval])",
     "legendFormat": "Miss count"
    }
   ]
  },
  {
   "title": "Web Cache size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vat_crawler_okhttp_cache_size_bytes",
     "legendFormat": "Cache size"
    }
   ]
  },
  {
   "title": "SMTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Names/sec",
     "type": "timeseries",
     "description": "Number of domain names visited by SMTP crawler per second.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "rate(smtp_analyzer_domains_done_total{instance=\"$instance\"}[$rate_interval])",
       "legendFormat": "Visits/sec"
      }
     ]
    },
    {
     "title": "SMTP crawls ongoing",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "smtp_crawls_ongoing{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IP's/sec",
     "type": "timeseries",
     "description": "Number of IP's visited per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "rate(smtp_crawl_ip_seconds_count{instance=\"$instance\"}[$rate_interval])",
       "legendFormat": "IP's visited"
      }
     ]
    },
    {
     "title": "SMTP crawls done",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 123 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smtp_analyzer_domains_done_total{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SMTP cache size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 123 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smtp_analyzer_cache_size{instance=\"$instance\"}",
       "legendFormat": "SMTP cache size"
      }
     ]
    },
    {
     "title": "SMTP visit duration ",
     "type": "timeseries",
     "description": "Avg time needed to visit one domain name",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(smtp_crawl_ip_seconds_sum{instance=\"$instance\"}[$rate_interval]) / rate(smtp_crawl_ip_seconds_count[$rate_interval])",
       "legendFormat": "Duration per IP"
      }
     ]
    }
   ]
  }
 ]
}