{
 "title": "Mercator",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Web crawler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(vat_crawler_okhttp_cache_hit_count[60s])",
     "legendFormat": "Hit count"
    },
    {
     "expr": "rate(vat_crawler_okhttp_cache_network_count[60s])",
     "legendFormat": "Miss count"
    },
    {
     "expr": "rate(vat_crawler_pages_fetched_total[60s])",
     "legendFormat": "Pages fetched"
    }
   ]
  },
  {
   "title": "SMTP IPs visited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(smtp_crawl_ip_seconds_count[60s])",
     "legendFormat": "IP's visited"
    }
   ]
  },
  {
   "title": "Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vat_crawler_page_body_fetched_seconds_sum[60s])/rate(vat_crawler_page_body_fetched_seconds_count[60s])",
     "legendFormat": "Avg duration page fetch"
    }
   ]
  },
  {
   "title": "SMTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(smtp_crawl_ip_seconds_sum{}[60s])/rate(smtp_crawl_ip_seconds_count{}[60s])",
     "legendFormat": "Duration per IP"
    }
   ]
  },
  {
   "title": "SMTP crawls done",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smtp_analyzer_domains_done_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMTP cache size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smtp_analyzer_cache_size", "legendFormat": "SMTP cache size" }
   ]
  },
  {
   "title": "TLS cache size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tls_crawler_scanresult_cache_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "tls_crawler_scanresult_cache_size",
     "legendFormat": "TLS cache size"
    },
    {
     "expr": "tls_crawler_scanresult_cache_misses_total",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "JMS Messages processed/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(jms_message_process_seconds_sum[$__rate_interval])/rate(jms_message_process_active_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vat_crawler_okhttp_cache_size_bytes",
     "legendFormat": "Cache size"
    }
   ]
  },
  {
   "title": "Visits saved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "save_visitResult_seconds_count{exception=\"none\"}",
     "legendFormat": "OK"
    },
    {
     "expr": "sum by(exception) (save_visitResult_seconds_count{exception!=\"none\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saving VisitResult",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(save_visitResult_seconds_sum{exception=\"none\"}[60s]) / rate(save_visitResult_seconds_count[60s])",
     "legendFormat": "Avg duration successful saves"
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_started_threads_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 42 },
   "targets": [
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "Daemon threads" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live threads" },
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Pages/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(vat_crawler_pages_fetched_total[60s])",
     "legendFormat": "fetched/sec"
    },
    {
     "expr": "rate(vat_crawler_pages_failed_total[60s])",
     "legendFormat": "Fetches failed/sec"
    }
   ]
  },
  {
   "title": "Pages fetched",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vat_crawler_pages_fetched_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMTP crawls ongoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 62 },
   "targets": [
    { "expr": "smtp_crawls_ongoing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pages failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vat_crawler_pages_failed_total", "legendFormat": "__auto" }
   ]
  }
 ]
}