apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
  {{- include "localstack.labels" . | nindent 4 }}
data:
  SERVICES: "sqs, s3"
  HOSTNAME_EXTERNAL: "localstack"
  DATA_DIR: "/tmp/localstack/data"
