apiVersion: v1
kind: Secret
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
  {{- include "localstack.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: "YWNjZXNzS2V5"
  AWS_SECRET_ACCESS_KEY: "c2VjcmV0S2V5"
