apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vat-crawler.fullname" . }}
  labels:
  {{- include "vat-crawler.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vat-crawler.selectorLabels" . | nindent 6 }}
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    - from:
        {{- with .from }}{{- . | toYaml | nindent 8 }}{{- else }} []{{- end }}
      ports:
        - protocol: "TCP"
          port: 8443
    {{- end }}
  egress:
    # vpc endpoints
    - ports:
        - port: 443
      to:
        {{- range .Values.global.vpc.endpoint_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
    # database
    - ports:
        - port: 5432
      to:
        {{- range .Values.global.vpc.db_cidr }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
    # vat crawling (should we allow all ports?)
    - ports:
        - port: 80
        - port: 443
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
  policyTypes:
    - Ingress
    - Egress
