create table page_visit
(
    id                             int8 generated by default as identity,
    visit_id                       uuid,
    domain_name                    varchar(255),
    crawl_started                  TIMESTAMPTZ,
    crawl_finished                 TIMESTAMPTZ,
    body_text                      TEXT,
    status_code                    int4,
    url                            varchar(500),
    path                           varchar(500),
    vat_values                     jsonb,
    primary key (id)
);

