apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smtp-crawler.fullname" . }}
  labels:
  {{- include "smtp-crawler.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
  GEO_IP_MAXMIND_LICENSE_KEY: {{ .Values.geoip.key }}
