name: Check vulnerabilities

on:
  push:
    branches:
      - main
      - persistent_queue
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: maven

#      - name: Run snyk
#        run: SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} mvn --batch-mode snyk:test
