apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wappalyzer.fullname" . }}
  labels:
  {{- include "wappalyzer.labels" . | nindent 4 }}
data:
  AWS_REGION: "{{ .Values.global.region }}"
  AWS_DEFAULT_REGION: "{{ .Values.global.region }}"
  AWS_STS_REGIONAL_ENDPOINTS: "regional"
  AWS_EC2_METADATA_DISABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wappalyzer.fullname" . }}-aws
  labels:
  {{- include "wappalyzer.labels" . | nindent 4 }}
data:
{{- if .Values.sqs_input_queue }}
  SQS_INPUT_QUEUE: "{{ .Values.sqs_input_queue }}"
{{- end }}
{{- if .Values.sqs_output_queue }}
  SQS_OUTPUT_QUEUE: "{{ .Values.sqs_output_queue }}"
{{- end }}
  NODE_ENV: "production"
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wappalyzer.fullname" . }}-local
  labels:
  {{- include "wappalyzer.labels" . | nindent 4 }}
data:
  S3_ENDPOINT: "http://localstack:4566"
  SQS_ENDPOINT: "http://localstack:4566"
  AWS_ACCESS_KEY_ID: "accessKey"
  AWS_SECRET_ACCESS_KEY: "secretKey"
  NODE_ENV: "kubernetes"
  WAPPALYZING_TIMEOUT: {{ .Values.wappalyzer_timeout | quote }}
