apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wappalyzer.fullname" . }}
  labels:
    {{- include "wappalyzer.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
    {{- include "wappalyzer.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "wappalyzer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wappalyzer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: http*/}}
{{/*            failureThreshold: 10*/}}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "wappalyzer.fullname" . }}
            {{ if eq .Values.global.environment "local" }}
            - configMapRef:
                name: "{{ include "wappalyzer.fullname" . }}-local"
            {{ else }}
            - configMapRef:
                name: "{{ include "wappalyzer.fullname" . }}-aws"
            {{ end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /app/dist/config
              name: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1000M
        - name: config
          emptyDir:
            sizeLimit: 10M
      dnsConfig:
        options:
          - name: ndots
            value: "1"
