apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ .Release.Namespace }}-{{ include "wappalyzer.fullname" . }}"
  labels:
    {{- include "wappalyzer.labels" . | nindent 4 }}
spec:
  readOnlyRootFilesystem: true
  privileged: false
  hostIPC: false
  hostPID: false
  hostNetwork: false
  hostPorts: []
  allowedHostPaths: []
  allowPrivilegeEscalation: false
  allowedCapabilities:
    - SYS_ADMIN
  requiredDropCapabilities:
    - all
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: 10000
        max: 65536
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 10000
        max: 65536
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 10000
        max: 65536
  seLinux:
    rule: 'RunAsAny'
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - secret
    - projected
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 'psp.{{ include "wappalyzer.fullname" . }}'
  labels:
    {{- include "wappalyzer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - '{{ .Release.Namespace }}-{{ include "wappalyzer.fullname" . }}'
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'psp.{{ include "wappalyzer.fullname" . }}'
  labels:
    {{- include "wappalyzer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'psp.{{ include "wappalyzer.fullname" . }}'
subjects:
  - kind: ServiceAccount
    name: {{ include "wappalyzer.serviceAccountName" . }}
